"""Add ScrapedProduct

Revision ID: 476efe05da39
Revises: 
Create Date: 2025-04-19 12:49:41.672205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '476efe05da39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_data')
    op.drop_table('products')
    with op.batch_alter_table('price_alert', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('product_url',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.alter_column('target_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('product_description', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('product_category',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)

    with op.batch_alter_table('product_description', schema=None) as batch_op:
        batch_op.alter_column('product_category',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('price_alert', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('target_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('product_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scraped_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
